apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-hub-prod
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: music-hub-backend=leogues/music-hub-backend
    argocd-image-updater.argoproj.io/music-hub-backend.update-strategy: semver
    argocd-image-updater.argoproj.io/music-hub-backend.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/music-hub-backend.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:envs/prod/music-hub/values.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: oracle-environments
  sources:
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      path: default
      helm:
        valueFiles:
          - $values/envs/prod/music-hub/values.yaml
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
