fullnameOverride: music-hub-app

image:
  repository: leogues/music-hub-frontend
  tag: "24"

service:
  port: 4200

livenessProbe: null
readinessProbe: null

autoscaling:
  enabled: true
  maxReplicas: 2

httpRoute:
  enabled: true
  parentRefs:
    - name: default
      namespace: gateway-system
      sectionName: https
  hostnames:
    - music.leogues.com.br
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

