apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/leogues/oracle-gitops.git
        revision: HEAD
        files:
          - path: envs/*/*/values.yaml
  template:
    metadata:
      name: "{{.path.basename}}"
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: "app={{.image.repository}}"
        argocd-image-updater.argoproj.io/app.update-strategy: semver
        argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
        argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: "helmvalues:/{{.path.path}}/values.yaml"
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      project: oracle-environments
      destination:
        namespace: "{{index .path.segments 1}}"
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/leogues/oracle-gitops.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/leogues/oracle-gitops.git
          targetRevision: main
          path: default
          helm:
            valueFiles:
              - $values/{{.path.path}}/values.yaml
      ignoreDifferences:
        - group: gateway.networking.k8s.io
          kind: HTTPRoute
          jqPathExpressions:
            - .spec.rules[].backendRefs[].weight
            - .metadata.labels."rollouts.argoproj.io/gatewayapi-canary"
        - group: ""
          kind: Service
          jqPathExpressions:
            - .spec.selector."rollouts-pod-template-hash"
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        syncOptions:
          - Validate=true
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
