fullnameOverride: live-link
image:
  repository: leogues/video-chat-backend
  tag: "53"
service:
  port: 8080
livenessProbe: null
readinessProbe: null
autoscaling:
  enabled: true
  maxReplicas: 2
httpRoute:
  enabled: true
  parentRefs:
  - name: default
    namespace: gateway-system
    sectionName: https
  hostnames:
  - live.leogues.com.br
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/
env:
  secretName: live-link-secret
