apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo=leogues/video-chat-frontend
    argocd-image-updater.argoproj.io/demo.update-strategy: semver
    argocd-image-updater.argoproj.io/demo.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/demo.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/envs/production/rollouts-demo/values.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: oracle-environments
  sources:
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      path: default
      helm:
        valueFiles:
          - $values/envs/production/rollouts-demo/values.yaml
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jqPathExpressions:
        - .spec.rules[].backendRefs[].weight
    - group: ""
      kind: Service
      jqPathExpressions:
        - .spec.selector."rollouts-pod-template-hash"
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
