apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    targetRevision: v1.5.1
    path: config/crd/standard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
