apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.20.2
      helm:
        valueFiles:
          - $values/platform/networking/cert-manager/values.yaml
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/leogues/oracle-gitops.git
      targetRevision: main
      path: platform/networking/cert-manager/extras
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
